language: julia
julia:
  - nightly
  - 1.5.0
codecov: true 
coveralls: true 

install: 
- export CC=gcc
- export CXX=g++
- export JULIA_NUM_THREADS=2
#- ./tools/travis-install-openmpi.sh
#- export MPIROOT=/home/travis/openmpi
#- export LD_LIBRARY_PATH=$MPIROOT/lib:$LD_LIBRARY_PATH                          
#- export LD_RUN_PATH=$MPIROOT/lib:$LD_RUN_PATH                                    
#- export PATH=$MPIROOT/bin:$PATH                                            
#- export CPATH=$MPIROOT/include:$CPATH                                            
#- export C_INCLUDE_PATH=$MPIROOT/include:$C_INCLUDE_PATH                          
#- export CPLUS_INCLUDE_PATH=$MPIROOT/include:$CPLUS_INCLUDE_PATH                  
#- export OBJC_INCLUDE_PATH=$MPIROOT/include:$OBJC_INCLUDE_PATH   
- ./tools/travis-install-eigen.sh
- export EIGEN_ROOT=/home/travis/eigen-install/include/eigen3
- ./tools/travis-install-boost.sh
- export BOOST_ROOT=/home/travis/boost-install
- ./tools/travis-install-libint.sh
- export LIBINT_ROOT=/home/travis/libint-install

script:
- julia -E "using Pkg; Pkg.instantiate()"
- julia -E "using Pkg; Pkg.build(\"JuliaChem\")"
#- cat ~/.julia/packages/MPI/z1lDn/deps/build.log
#- cd deps && julia build.jl && cd ../
- julia --code-coverage test/runtests-travis.jl

after_success:
- julia -e 'using Pkg; cd(Pkg.dir("JuliaChem")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
