language: julia
julia:
  - nightly
  - 1.5.0
codecov: true 
coveralls: true 

install: 
- ./tools/travis-install-openmpi.sh
- export MPIROOT=/home/travis/openmpi
- export LD_LIBRARY_PATH=$MPIROOT/lib:$LD_LIBRARY_PATH                          
- export LD_RUN_PATH=$MPIROOT/lib:$LD_RUN_PATH                                    
- export PATH=$MPIROOT/bin:$PATH                                            
- export CPATH=$MPIROOT/include:$CPATH                                            
- export C_INCLUDE_PATH=$MPIROOT/include:$C_INCLUDE_PATH                          
- export CPLUS_INCLUDE_PATH=$MPIROOT/include:$CPLUS_INCLUDE_PATH                  
- export OBJC_INCLUDE_PATH=$MPIROOT/include:$OBJC_INCLUDE_PATH   
- ./tools/travis-install-simint.sh
- export SIMINT=/home/travis/simint-install
- export CC=gcc
- export CXX=g++

script:
- julia -E "using Pkg; Pkg.instantiate()"
#- cd deps && julia build.jl && cd ../
- julia --code-coverage test/runtests-travis.jl

after_success:
- JULIA_NUM_THREADS=8 julia -e 'using Pkg; cd(Pkg.dir("JuliaChem")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
